### PR TITLE
Fix `ObjectEnum.asPairs` behaving incorrectly.

### LINKED ISSUE #4: Fix camelcase name compatibility
This:

``` python
class Foo(object):
  def as_pairs(self): ...
  asPairs = as_pairs
```

is not the same as this:

``` python
class Foo(object):
  def as_pairs(self): ...
  def asPairs(self): return self.as_pairs()
```

### PR DESCRIPTION
**Pull request by jonathanj**
Also emit deprecating warnings for all the old camelcase methods.

Fixes #4.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/fusionapp/fusion-util/5)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[fusion_util/test/test_enums.py, line 44 [r2]](https://reviewable.io:443/reviews/fusionapp/fusion-util/5#-KCeuvQxUOOHF_E-eP19:-KCeuvQytGPeSeEVn6Qz:1702547657) ([raw file](https://github.com/fusionapp/fusion-util/blob/b6d475061447fd8ef04b357190d340985d5ae080/fusion_util/test/test_enums.py#L44)):_
This should include `str()` of `self.warnings_matcher`.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-util/5)_

**Comment by jonathanj** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[fusion_util/test/test_enums.py, line 44 [r2]](https://reviewable.io:443/reviews/fusionapp/fusion-util/5#-KCeuvQxUOOHF_E-eP19:-KCevmKL480Zefe0C2at:-499146009) ([raw file](https://github.com/fusionapp/fusion-util/blob/b6d475061447fd8ef04b357190d340985d5ae080/fusion_util/test/test_enums.py#L44)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-util/5)_

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[fusion_util/test/test_enums.py, line 44 [r3]](https://reviewable.io:443/reviews/fusionapp/fusion-util/5#-KCezvLsfMp0eEip9Akj:-KCezvLtoNx2qFLr2Ca6:66877619) ([raw file](https://github.com/fusionapp/fusion-util/blob/8aba8bee7f44f863371c3a8b1fbbf8ddd6e68fef/fusion_util/test/test_enums.py#L44)):_
Sorry for the nitpicking, but you can write this as just 'Warnings({!s}).format(self.warnings_matcher)` which I think is more concise.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-util/5)_

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-util/5)_

**Comment by jonathanj** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[fusion_util/test/test_enums.py, line 44 [r3]](https://reviewable.io:443/reviews/fusionapp/fusion-util/5#-KCezvLsfMp0eEip9Akj:-KCf6BHOdBzw7CCtlhRd:-499146009) ([raw file](https://github.com/fusionapp/fusion-util/blob/8aba8bee7f44f863371c3a8b1fbbf8ddd6e68fef/fusion_util/test/test_enums.py#L44)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fusionapp/fusion-util/5)_

**Pull request merged**
